nacos:
  host: 192.168.0.2
  port: 8848
  namespace: c1872978-d51c-4188-a497-4e0cd20b97d5
  user: nacos
  password: nacos
  dataid: user-web.json
  group: pro
database:
  driverName: mysql
  host: localhost
  port: 3306
  db: test
  username: root
  password: root
  charset: utf8mb4
  loc: Asia/Shanghai